default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: cozy_nest_living_db

test:
  <<: *default
  database: cozy_nest_living_test


production:
  primary: &primary_production
    <<: *default
    database: cozy_nest_living_production
    username: cozy_nest_living
    password: <%= ENV["COZY_NEST_LIVING_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cozy_nest_living_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cozy_nest_living_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cozy_nest_living_production_cable
    migrations_paths: db/cable_migrate
